// Generated by CoffeeScript 1.3.3
(function() {
  var uuid;

  uuid = require('node-uuid');

  module.exports = function(req, res) {
    var client, rid, summoners, _get;
    _get = function(msg) {
      var data;
      if (msg.event === ("" + rid + "__finished")) {
        data = {
          status: 200,
          body: msg.data,
          requests: msg.extra.requests
        };
        client.removeListener('message', _get);
        res.charset = 'utf8';
        res.contentType('json');
        return res.send(data.body);
      }
    };
    client = req.lolclient;
    rid = uuid.v4();
    summoners = req.query.ids.split(',').map(Number);
    client.on('message', _get);
    return client.send({
      'event': 'get',
      'model': 'PlayerNames',
      'query': {
        'summoners': summoners
      },
      'uuid': rid
    });
  };

}).call(this);
