// Generated by CoffeeScript 1.3.3
(function() {
  var MasteryBook, PlayerNames, PlayerStats, RecentGames, RunePage, Search, SpectatorInfo, Summoner, has_key, json, util,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  json = JSON.stringify;

  util = require('util');

  has_key = function(obj, key) {
    return obj.hasOwnProperty(key);
  };

  PlayerNames = (function() {

    function PlayerNames(cb, options) {
      this.cb = cb;
      this.get = __bind(this.get, this);

      this.parse = __bind(this.parse, this);

      if (options != null) {
        if (options.hasOwnProperty('client')) {
          this.client = options.client;
        }
        if (options.hasOwnProperty('summoners')) {
          this.summoners = summoners;
        }
      }
      this.data = [];
    }

    PlayerNames.prototype.parse = function() {};

    PlayerNames.prototype.get = function(args) {
      var _this = this;
      this.summoners = args.summoners;
      return this.client.getSummonerName(this.summoners, function(err, result) {
        var data;
        if (err != null) {
          data = err;
        } else {
          data = result.data;
        }
        return _this.cb(data, {
          requests: 1
        });
      });
    };

    return PlayerNames;

  })();

  PlayerStats = (function() {

    function PlayerStats(cb, options) {
      this.cb = cb;
      this.toJSON = __bind(this.toJSON, this);

      this.get = __bind(this.get, this);

      this.parse = __bind(this.parse, this);

      if (options != null) {
        if (options.hasOwnProperty('client')) {
          this.client = options.client;
        }
        if (options.hasOwnProperty('stats')) {
          this.org = options.stats;
          this.account_id = this.org.userId.value;
        }
      }
      this.data = [];
    }

    PlayerStats.prototype.parse = function() {
      var current, game_type, stat, stats, _i, _j, _len, _len1, _ref, _ref1;
      this.data = [];
      _ref = this.org.playerStatSummaries.object.playerStatSummarySet.data;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        game_type = _ref[_i];
        stats = game_type.object;
        current = {
          'game_type': stats.playerStatSummaryTypeString,
          'rating': stats.rating,
          'rating_max': stats.maxRating,
          'wins': stats.wins,
          'losses': stats.losses,
          'leaves': stats.leaves,
          'aggregated_stats': {}
        };
        _ref1 = stats.aggregatedStats.object.stats.data;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          stat = _ref1[_j];
          current['aggregated_stats'][stat.object.statType.toLowerCase()] = stat.object.value.value;
        }
        this.data.push(current);
      }
      return this.data;
    };

    PlayerStats.prototype.get = function(args) {
      var account_id,
        _this = this;
      account_id = args.account_id;
      return this.client.getSummonerStats(account_id, function(err, result) {
        var data;
        if (err != null) {
          data = err;
        } else {
          _this.org = result.object;
          _this.account_id = _this.org.userId.value;
          _this.parse();
        }
        return _this.cb(_this.data, {
          account_id: _this.account_id,
          requests: 1
        });
      });
    };

    PlayerStats.prototype.toJSON = function() {
      return json(this.data);
    };

    return PlayerStats;

  })();

  RecentGames = (function() {

    function RecentGames(cb, options) {
      this.cb = cb;
      this.toJSON = __bind(this.toJSON, this);

      this.get = __bind(this.get, this);

      this.parse = __bind(this.parse, this);

      if (options.hasOwnProperty('client')) {
        this.client = options.client;
      }
      if (options.hasOwnProperty('games')) {
        this.org = games;
        this.account_id = this.org.userId.value;
      }
      this.data = [];
    }

    RecentGames.prototype.parse = function() {
      var current, game, key, ogame, player, stat, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _ref2;
      this.data = [];
      _ref = this.org.gameStatistics.data;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        ogame = _ref[_i];
        game = ogame.object;
        current = {
          'id': game.gameId.value,
          'game_map': game.gameMapId,
          'game_mode': game.gameMode,
          'game_type': game.gameType,
          'team': game.teamId.value === 100 ? 'blue' : 'purple',
          'afk': game.afk,
          'leaver': game.leaver,
          'ip_earned': game.ipEarned.value,
          'xp_earned': game.experienceEarned.value,
          'boost_ip': game.boostIpEarned.value,
          'boost_xp': game.boostXpEarned.value,
          'champion': game.championId.value,
          'date': game.createDate,
          'players': (function() {
            var _j, _len1, _ref1, _results;
            _ref1 = game.fellowPlayers.data;
            _results = [];
            for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
              player = _ref1[_j];
              _results.push(player.object.summonerId.value);
            }
            return _results;
          })(),
          'summoner_level': game.level.value,
          'premade_size': game.premadeSize,
          'premade_team': game.premadeTeam,
          'skin_index': game.skinIndex,
          'skin_name': game.skinName,
          'summoner_spell_one': game.spell1.value,
          'summoner_spell_two': game.spell2.value,
          'queue_length': game.timeInQueue,
          'queue_type': game.queueType,
          'ping': game.userServerPing,
          'stats': {}
        };
        _ref1 = game.statistics.data;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          stat = _ref1[_j];
          current['stats'][stat.object.statType.toLowerCase()] = stat.object.value.value;
        }
        _ref2 = ['num_deaths', 'champions_killed', 'assists', 'largest_critical_strike', 'largest_killing_spree', 'largest_multi_kill', 'item0', 'item1', 'item2', 'item3', 'item4', 'item5', 'minions_killed', 'gold_earned', 'physical_damage_dealt_player', 'magic_damage_dealt_player', 'physical_damage_taken', 'magic_damage_taken', 'total_heal', 'total_time_spent_dead', 'neutral_minions_killed', 'turrets_killed', 'inhibitors_destroyed', 'lose', 'win'];
        for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
          key = _ref2[_k];
          if (!has_key(current.stats, key)) {
            current.stats[key] = 0;
          }
        }
        current.stats.damage_taken = current.stats.physical_damage_taken + current.stats.magic_damage_taken;
        current.stats.damage_dealt = current.stats.physical_damage_dealt_player + current.stats.magic_damage_dealt_player;
        this.data.push(current);
        this.data.sort(function(a, b) {
          if (a.id > b.id) {
            return -1;
          } else if (a.id < b.id) {
            return 1;
          } else {
            return 0;
          }
        });
      }
      return this.data;
    };

    RecentGames.prototype.get = function(args) {
      var account_id,
        _this = this;
      account_id = args.account_id;
      return this.client.getMatchHistory(account_id, function(err, result) {
        var data;
        if (err != null) {
          console.log('Error'.red + err);
          data = err;
        } else {
          _this.org = result.object;
          _this.account_id = _this.org.userId.value;
          _this.parse();
        }
        return _this.cb(_this.data, {
          account_id: _this.account_id,
          requests: 1
        });
      });
    };

    RecentGames.prototype.toJSON = function() {
      return json(this.data);
    };

    return RecentGames;

  })();

  Summoner = (function() {

    function Summoner(cb, options) {
      this.cb = cb;
      this.toJSON = __bind(this.toJSON, this);

      this.get = __bind(this.get, this);

      this.parse = __bind(this.parse, this);

      if (options != null) {
        if (options.hasOwnProperty('client')) {
          this.client = options.client;
        }
        if (options.hasOwnProperty('summoner')) {
          this.summoner = options.summoner;
          this.account_id = this.summoner.acctId.value;
        }
        if (options.extra != null) {
          if (options.extra.runes != null) {
            this.runes = options.extra.runes;
          }
          if (options.extra.masteries != null) {
            this.masteries = options.extra.masteries;
          }
        }
      }
      this.data = {};
      this.requests = 0;
    }

    Summoner.prototype.parse = function() {
      var current;
      this.data = {};
      current = {
        'account_id': this.summoner.acctId.value,
        'summoner_id': this.summoner.sumId.value,
        'internal_name': this.summoner.internalName,
        'name': this.summoner.name,
        'level': this.org.object.summonerLevelAndPoints.object.summonerLevel.value,
        'profile_icon': this.summoner.profileIconId,
        'season_one_tier': this.summoner.seasonOneTier
      };
      this.data = current;
      return this.data;
    };

    Summoner.prototype.get = function(args) {
      var found_account_id,
        _this = this;
      found_account_id = function() {
        return _this.client.getSummonerData(_this.account_id, function(err, result) {
          var extra;
          if (err != null) {
            _this.data = err;
          } else {
            _this.org = result;
            try {
              _this.summoner = result.object.summoner.object;
              _this.account_id = _this.summoner.acctId.value;
            } catch (e) {
              console.log(e);
              console.log(util.inspect(result, false, 10, true));
            }
            _this.parse();
          }
          extra = {
            requests: _this.requests + 1
          };
          if (_this.runes) {
            extra['runes'] = new RunePage({
              'book': _this.org.object.spellBook.object
            }).parse();
          }
          return _this.cb(_this.data, extra);
        });
      };
      if (has_key(args, 'account_id')) {
        this.account_id = args.account_id;
        return found_account_id();
      } else if (has_key(args, 'name')) {
        return this.client.getSummonerByName(args.name, function(err, result) {
          _this.requests += 1;
          if (err != null) {
            _this.data = err;
            return _this.cb(_this.data, {
              requests: _this.requests
            });
          } else {
            _this.account_id = result.object.acctId.value;
            return found_account_id();
          }
        });
      }
    };

    Summoner.prototype.toJSON = function() {
      return json(this.data);
    };

    return Summoner;

  })();

  Search = (function() {

    function Search(cb, options) {
      this.cb = cb;
      this.toJSON = __bind(this.toJSON, this);

      this.get = __bind(this.get, this);

      this.parse = __bind(this.parse, this);

      if (options != null) {
        if (has_key(options, 'client')) {
          this.client = options.client;
        }
        if (has_key(options, 'search')) {
          this.search = options.search;
          this.account_id = this.search.account_id;
        }
      }
      this.data = {};
    }

    Search.prototype.parse = function() {
      var current;
      console.log(this.search);
      this.data = {};
      current = {
        'account_id': this.search.acctId.value,
        'summoner_id': this.search.summonerId.value,
        'internal_name': this.search.internalName,
        'name': this.search.name,
        'level': this.search.summonerLevel.value,
        'profile_icon': this.search.profileIconId,
        'region': this.client.options.region
      };
      this.data = current;
      return this.data;
    };

    Search.prototype.get = function(args) {
      var name,
        _this = this;
      name = args.name;
      return this.client.getSummonerByName(name, function(err, result) {
        if (err != null) {
          _this.data = err;
        } else if (err === null && result === null) {
          _this.data = {};
        } else {
          _this.account_id = result.object.acctId.value;
          _this.search = result.object;
          _this.parse();
        }
        return _this.cb(_this.data, {
          requests: 1
        });
      });
    };

    Search.prototype.toJSON = function() {
      return json(this.data);
    };

    return Search;

  })();

  RunePage = (function() {

    function RunePage(options) {
      this.toJSON = __bind(this.toJSON, this);

      this._rsort = __bind(this._rsort, this);

      this._msort = __bind(this._msort, this);

      this.parse = __bind(this.parse, this);
      if (options != null) {
        if (has_key(options, 'client')) {
          this.client = options.client;
        }
        if (has_key(options, 'book')) {
          this.book = options.book;
        }
      }
      this.data = [];
    }

    RunePage.prototype.parse = function() {
      var current, page, rune, tmp, _i, _j, _len, _len1, _ref, _ref1;
      this.data = [];
      _ref = this.book.bookPages.data;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        page = _ref[_i];
        page = page.object;
        if (page.name.match(/@@!PaG3!@@\d+/)) {
          continue;
        }
        current = {
          'id': page.pageId.value,
          'name': page.name,
          'created': page.createDate,
          'slots': []
        };
        _ref1 = page.slotEntries.data;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          rune = _ref1[_j];
          rune = rune.object;
          tmp = {
            'slot': rune.runeSlotId,
            'id': rune.runeId
          };
          current.slots.push(tmp);
        }
        current.slots.sort(this._rsort);
        this.data.push(current);
      }
      this.data.sort(this._msort);
      return this.data;
    };

    RunePage.prototype._msort = function(a, b) {
      if (a.id < b.id) {
        return -1;
      } else if (a.id === b.id) {
        return 0;
      } else {
        return 1;
      }
    };

    RunePage.prototype._rsort = function(a, b) {
      if (a.slot < b.slot) {
        return -1;
      } else if (a.slot === b.slot) {
        return 0;
      } else {
        return 1;
      }
    };

    RunePage.prototype.toJSON = function() {
      return json(this.data);
    };

    return RunePage;

  })();

  MasteryBook = (function() {

    function MasteryBook(cb, options) {
      this.cb = cb;
      this.toJSON = __bind(this.toJSON, this);

      this._msort = __bind(this._msort, this);

      this.get = __bind(this.get, this);

      this.parse = __bind(this.parse, this);

      if (options != null) {
        if (has_key(options, 'client')) {
          this.client = options.client;
        }
        if (has_key(options, 'book')) {
          this.book = options.book;
        }
      }
    }

    MasteryBook.prototype.parse = function() {
      var current, id, page, talent, tmp, _i, _j, _len, _len1, _ref, _ref1;
      this.data = {};
      current = [];
      _ref = this.book.data;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        page = _ref[_i];
        page = page.object;
        if (page.name.match(/@@!PaG3!@@\d+/)) {
          continue;
        }
        id = page.pageId.value;
        tmp = {
          'id': id,
          'name': page.name,
          'current': page.current,
          'talents': []
        };
        _ref1 = page.talentEntries.data;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          talent = _ref1[_j];
          talent = talent.object;
          tmp.talents.push({
            'id': talent.talentId,
            'rank': talent.rank
          });
        }
        tmp.talents.sort(this._msort);
        current.push(tmp);
      }
      current.sort(this._msort);
      this.data = current;
      return this.data;
    };

    MasteryBook.prototype.get = function(args) {
      var _this = this;
      this.summoner_id = args.summoner_id;
      this.account_id = args.account_id;
      return this.client.getMasteryBook(this.summoner_id, function(err, result) {
        if (err != null) {
          _this.data = err;
        } else {
          _this.book = result.object.bookPages;
          _this.parse();
        }
        return _this.cb(_this.data, {
          'account_id': _this.account_id,
          requests: 1
        });
      });
    };

    MasteryBook.prototype._msort = function(a, b) {
      if (a.id < b.id) {
        return -1;
      } else if (a.id === b.id) {
        return 0;
      } else {
        return 1;
      }
    };

    MasteryBook.prototype.toJSON = function() {
      return json(this.data);
    };

    return MasteryBook;

  })();

  SpectatorInfo = (function() {

    function SpectatorInfo(cb, options) {
      this.cb = cb;
      this.toJSON = __bind(this.toJSON, this);

      this.get = __bind(this.get, this);

      this.parse = __bind(this.parse, this);

      if (options != null) {
        if (has_key(options, 'client')) {
          this.client = options.client;
        }
        if (has_key(options, 'info')) {
          this.info = options.info;
        }
      }
      this.data = {};
    }

    SpectatorInfo.prototype.parse = function() {
      var current, regions;
      this.data = {};
      regions = {
        'na': 'NA1',
        'euw': 'EUW1',
        'eune': 'EUN1'
      };
      current = {
        'key': this.info.playerCredentials.object.observerEncryptionKey,
        'ip': this.info.playerCredentials.object.observerServerIp,
        'port': this.info.playerCredentials.object.observerServerPort,
        'game_id': this.info.playerCredentials.object.gameId.value,
        'region': regions[this.client.options.region],
        'name': this.info.game.object.name
      };
      this.data = current;
      return this.data;
    };

    SpectatorInfo.prototype.get = function(args) {
      var name,
        _this = this;
      name = args.name;
      return this.client.getSpectatorInfo(name, function(err, result) {
        if (args.debug != null) {
          console.log("err:" + (util.inspect(err, false, 10, true)));
        }
        if (args.debug != null) {
          console.log("res:" + (util.inspect(result, false, 10, true)));
        }
        if (err != null) {
          _this.data = {
            'error': err
          };
        } else {
          _this.info = result.object;
          _this.parse();
        }
        return _this.cb(_this.data, {
          requests: 1
        });
      });
    };

    SpectatorInfo.prototype.toJSON = function() {
      return json(this.data);
    };

    return SpectatorInfo;

  })();

  exports.PlayerNames = PlayerNames;

  exports.PlayerStats = PlayerStats;

  exports.RecentGames = RecentGames;

  exports.Summoner = Summoner;

  exports.RunePage = RunePage;

  exports.Search = Search;

  exports.MasteryBook = MasteryBook;

  exports.SpectatorInfo = SpectatorInfo;

}).call(this);
