// Generated by CoffeeScript 1.3.3
(function() {

  exports.mass_update = require('./mass_update');

  exports.get_names = require('./get_names');

  exports.search = require('./search');

  exports.spectate = require('./spectate');

  exports.masterybook = require('./masterybook');

  exports.index = function(req, res) {
    res.charset = 'utf8';
    res.contentType('json');
    return res.send(JSON.stringify(req.lolclient_status));
  };

  exports.status = function(req, res) {
    res.charset = 'utf8';
    res.contentType('json');
    return res.send(JSON.stringify(req.bridge_status));
  };

}).call(this);
