// Generated by CoffeeScript 1.3.3
(function() {
  var LolClient, a, client, options, summoner, util;

  LolClient = require('./lol-client');

  util = require('util');

  options = {
    region: 'na',
    username: 'thosebananas',
    password: 'penis2',
    version: '1.59.12_04_30_11_00'
  };

  summoner = {
    name: 'The Cat Shark'
  };

  client = new LolClient(options);

  a = [];

  client.on('connection', function() {
    return client.getSummonerName([115259], function(err, result) {
      console.log('#######################');
      console.log(err);
      console.log('#######################');
      console.log(result.object);
      a = result;
      console.log('#######################');
      return null;
    });
  });

  client.connect();

}).call(this);
