// Generated by CoffeeScript 1.3.3
(function() {
  var LolClient, a, client, fs, options, summoner, util;

  LolClient = require('./lol-client');

  util = require('util');

  fs = require('fs');

  options = {
    region: 'na',
    username: 'intoleagues',
    password: 'penis2',
    version: '1.63.12_07_15_18_46'
  };

  summoner = {
    name: 'eatpie75',
    account_id: 142098,
    summoner_id: 115259
  };

  client = new LolClient(options);

  a = [];

  client.on('connection', function() {
    console.log('Connected');
    return client.getSummonerData(summoner.account_id, function(err, result) {
      return fs.writeFileSync('getSummonerData.json', JSON.stringify(result), 'utf8');
    });
  });

  client.connect();

  module.exports = client;

}).call(this);
