// Generated by CoffeeScript 1.3.3
(function() {
  var LolClient, a, client, options, summoner, util;

  LolClient = require('./lol-client');

  util = require('util');

  options = {
    region: 'na',
    username: 'thosebananas',
    password: 'penis2',
    version: '1.60.12_05_22_19_12'
  };

  summoner = {
    name: 'eatpie75'
  };

  client = new LolClient(options);

  a = [];

  client.connect();

  module.exports = client;

}).call(this);
