// Generated by CoffeeScript 1.3.3
(function() {
  var LolClient, client, options, summoner, summoners, util, _i, _len, _ref;

  LolClient = require('./lol-client');

  util = require('util');

  options = {
    region: 'na',
    username: 'dotaesnumerouno',
    password: 'penis2',
    version: '1.59.12_04_30_11_00'
  };

  client = new LolClient(options);

  summoners = [];

  _ref = process.argv.slice(2);
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    summoner = _ref[_i];
    summoners.push(summoner / 1);
  }

  client.on('connection', function() {
    return client.getSummonerName(summoners, function(err, result) {
      console.log(util.format('%j', result.data));
      return process.exit();
    });
  });

  client.connect();

}).call(this);
