// Generated by CoffeeScript 1.3.3
(function() {
  var bind_events, child_process, colors, events, server, servers, tmp, _i, _len, _log;

  child_process = require('child_process');

  colors = require('colors');

  events = require('events');

  _log = function(msg) {
    var blank, d, info, time;
    blank = '                                                 ';
    d = new Date();
    time = (" " + (d.getFullYear()) + "/" + (d.getMonth() + 1) + "/" + (d.getDate()) + " " + (d.getHours()) + ":" + (d.getMinutes() < 10 ? '0' + d.getMinutes() : d.getMinutes()) + ":" + (d.getSeconds() < 10 ? '0' + d.getSeconds() : d.getSeconds())).white;
    info = (msg.server + time + blank).slice(0, 49);
    return console.log(info + " | " + msg.text);
  };

  servers = [
    {
      username: 'dotaesnumerouno',
      password: 'penis2',
      region: 'na',
      port: 8081,
      version: '1.60.12_05_22_19_12'
    }, {
      username: 'thosebananas',
      password: 'penis2',
      region: 'na',
      port: 8082,
      version: '1.60.12_05_22_19_12'
    }, {
      username: 'dotaesnumerouno',
      password: 'penis2',
      region: 'euw',
      port: 8083,
      version: '1.59.12_05_04_10_59'
    }
  ];

  bind_events = function(server) {
    return server.on('exit', function(code, signal) {
      return console.log(code, signal);
    }).on('message', function(msg) {
      if (msg.event === 'log') {
        return _log(msg);
      }
    });
  };

  for (_i = 0, _len = servers.length; _i < _len; _i++) {
    server = servers[_i];
    tmp = child_process.fork('learn.js', ['--username', server.username, '--password', server.password, '--region', server.region, '--port', server.port, '--version', server.version]);
    bind_events(tmp);
  }

}).call(this);
