// Generated by CoffeeScript 1.3.3
(function() {
  var GetNames, GetSummonerData, MassUpdate, RecentGames, Search, colors, events, has_key, models, qs, sleep, util, uuid, views, _log,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  colors = require('colors');

  events = require('events');

  qs = require('querystring');

  util = require('util');

  uuid = require('node-uuid');

  models = require('./lib/models');

  _log = function(text) {
    return process.send({
      event: 'log',
      server: "" + options.region + ":" + options.username,
      text: text
    });
  };

  has_key = function(obj, key) {
    return obj.hasOwnProperty(key);
  };

  sleep = function(ms) {
    var d, startTime;
    d = startTime = new Date().getTime();
    while (d < startTime + ms) {
      d = new Date().getTime();
    }
    return true;
  };

  GetNames = (function() {

    function GetNames(query, local_client, ev, request, response) {
      this.get = __bind(this.get, this);

      this.go = __bind(this.go, this);
      this.uuid = uuid.v4();
      this.client = local_client;
      this.ev = ev;
      this.request = request;
      this.response = response;
      this.summoners = qs.parse(query)['ids'].split(',').map(Number);
    }

    GetNames.prototype.go = function() {
      this.client.on('message', this.get);
      return this.client.send({
        event: 'get',
        model: 'PlayerNames',
        query: {
          summoners: this.summoners
        },
        uuid: this.uuid
      });
    };

    GetNames.prototype.get = function(msg) {
      var data;
      if (msg.event === ("" + this.uuid + "__finished")) {
        data = {
          status: 200,
          body: msg.data
        };
        this.ev.emit('finished', data, this.request, this.response);
        return this.client.removeListener('message', this.get);
      }
    };

    return GetNames;

  })();

  MassUpdate = (function() {

    function MassUpdate(query, local_client, ev, request, response) {
      this.throttled = __bind(this.throttled, this);

      this._next = __bind(this._next, this);

      this.get = __bind(this.get, this);

      this.go = __bind(this.go, this);

      var account, name;
      this.uuid = [uuid.v4(), uuid.v4(), uuid.v4()];
      this.client = local_client;
      this.ev = ev;
      this.request = request;
      this.response = response;
      this.query = qs.parse(query);
      this.data = {
        status: 200,
        body: {
          errors: [],
          accounts: {}
        }
      };
      this.running_queries = 0;
      this.queue = [];
      if (this.query['accounts'] != null) {
        this.queue = this.queue.concat((function() {
          var _i, _len, _ref, _results;
          _ref = this.query['accounts'].split(',');
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            account = _ref[_i];
            _results.push({
              account_id: account
            });
          }
          return _results;
        }).call(this));
      }
      if (this.query['names'] != null) {
        this.queue = this.queue.concat((function() {
          var _i, _len, _ref, _results;
          _ref = this.query['names'].split(',');
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            name = _ref[_i];
            _results.push({
              'name': name
            });
          }
          return _results;
        }).call(this));
      }
      if (this.query['games'] != null) {
        this.games = 1;
      } else {
        this.games = 0;
      }
      this.ev.on('next', this._next);
      this.client.on('message', this.get);
    }

    MassUpdate.prototype.go = function() {
      return this.ev.emit('next');
    };

    MassUpdate.prototype.get = function(msg) {
      var summoner;
      if (msg.event === ("" + this.uuid[0] + "__finished")) {
        summoner = msg.data;
        if (!has_key(this.data.body.accounts, summoner.account_id)) {
          this.data.body.accounts[summoner.account_id] = {};
        }
        this.data.body.accounts[summoner.account_id].profile = summoner;
        this.client.send({
          event: 'get',
          model: 'PlayerStats',
          query: {
            account_id: summoner.account_id
          },
          uuid: this.uuid[1]
        });
        if (this.games) {
          this.running_queries += 1;
          return this.client.send({
            event: 'get',
            model: 'RecentGames',
            query: {
              account_id: summoner.account_id
            },
            uuid: this.uuid[2]
          });
        }
      } else if (msg.event === ("" + this.uuid[1] + "__finished")) {
        this.data.body.accounts[msg.extra.account_id].stats = msg.data;
        this.running_queries -= 1;
        return this.ev.emit('next');
      } else if (msg.event === ("" + this.uuid[2] + "__finished")) {
        this.running_queries -= 1;
        this.data.body.accounts[msg.extra.account_id].games = msg.data;
        return this.ev.emit('next');
      } else if (msg.event === 'throttled') {
        return this.throttled();
      }
    };

    MassUpdate.prototype._next = function() {
      var key;
      if (this.running_queries < 5 && this.queue.length > 0) {
        this.running_queries += 1;
        key = this.queue.shift();
        console.log(key);
        try {
          return this.client.send({
            event: 'get',
            model: 'Summoner',
            query: key,
            uuid: this.uuid[0]
          });
        } catch (error) {
          return console.log(error);
        }
      } else if (this.running_queries === 0 && this.queue.length === 0) {
        this.ev.emit('finished', this.data, this.request, this.response);
        this.ev.removeAllListeners('fetched').removeListener('next', this._next);
        return this.client.removeListener('message', this.get);
      }
    };

    MassUpdate.prototype.throttled = function() {
      this.client.removeListener('message', this.get);
      this.response.writeHead(500);
      return this.response.end();
    };

    return MassUpdate;

  })();

  RecentGames = (function() {

    function RecentGames(query, local_client, ev, request, response) {
      this.go = __bind(this.go, this);
      this.client = local_client;
      this.ev = ev;
      this.request = request;
      this.response = response;
      this.query = qs.parse(query);
      this.account = Number(this.query['account']);
      this.data = {};
    }

    RecentGames.prototype.go = function() {
      var games,
        _this = this;
      _log('Fetching games'.yellow);
      games = new models.RecentGames({
        client: this.client
      });
      games.on('finished', function(result) {
        var data;
        data = {
          status: 200,
          body: result
        };
        return _this.ev.emit('finished', data, _this.request, _this.response);
      });
      games.get(this.account);
      return false;
    };

    return RecentGames;

  })();

  GetSummonerData = (function() {

    function GetSummonerData(query, local_client, ev, request, response) {
      this.go = __bind(this.go, this);
      this.client = local_client;
      this.ev = ev;
      this.request = request;
      this.response = response;
      this.query = qs.parse(query);
      if (this.query['account'] != null) {
        this.key = {
          account_id: Number(this.query['account'])
        };
      } else if (this.query['name'] != null) {
        this.key = {
          name: this.query['name']
        };
      }
      if (this.query['runes'] != null) {
        this.runes = 1;
      } else {
        this.runes = 0;
      }
      this.data = {};
    }

    GetSummonerData.prototype.go = function() {
      var summoner_data,
        _this = this;
      summoner_data = new models.Summoner({
        client: this.client
      });
      summoner_data.on('finished', function(result) {
        _this.data = {
          status: 200,
          body: result
        };
        if (_this.runes) {
          _this.data.body['runes'] = new models.RunePage(summoner_data.org.object.spellBook.object).parse();
        }
        return _this.ev.emit('finished', _this.data, _this.request, _this.response);
      });
      return summoner_data.get(this.key);
    };

    return GetSummonerData;

  })();

  Search = (function() {

    function Search(query, local_client, ev, request, response) {
      this.get = __bind(this.get, this);

      this.go = __bind(this.go, this);
      this.uuid = uuid.v4();
      this.client = local_client;
      this.ev = ev;
      this.request = request;
      this.response = response;
      this.name = qs.parse(query)['name'];
    }

    Search.prototype.go = function() {
      this.client.on('message', this.get);
      return this.client.send({
        event: 'get',
        model: 'Search',
        query: {
          name: this.name
        },
        uuid: this.uuid
      });
    };

    Search.prototype.get = function(msg) {
      var data;
      if (msg.event === ("" + this.uuid + "__finished")) {
        data = {
          status: 200,
          body: msg.data
        };
        this.ev.emit('finished', data, this.request, this.response);
        return this.client.removeListener('message', this.get);
      }
    };

    return Search;

  })();

  views = {
    '/get_names/': GetNames,
    '/mass_update/': MassUpdate,
    '/recent_games/': RecentGames,
    '/get_data/': GetSummonerData,
    '/search/': Search
  };

  module.exports = views;

}).call(this);
